# Generated by Django 4.2.3 on 2023-07-26 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('image', models.ImageField(blank=True, upload_to='cat_img')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(blank=True, max_length=40)),
                ('org_price', models.FloatField(blank=True)),
                ('sell_price', models.FloatField(blank=True)),
                ('quantity', models.IntegerField()),
                ('img', models.ImageField(upload_to='pictures')),
                ('pro_desc', models.TextField()),
                ('catagory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.category')),
            ],
        ),
    ]
