# Generated by Django 4.2.3 on 2023-08-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_cart_id_alter_products_pname_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='stocks',
            field=models.IntegerField(default=10),
        ),
    ]
